### PR TITLE
Update for CUDA 10.2

### PR DESCRIPTION
**Pull request by mike-wendt**
Update paths, links, and info for CUDA 10.2

Published linux package here if you want to pull/test: https://anaconda.org/nvidia/cudatoolkit/files

### CODE REVIEW

**Comment by jakirkham** [comment]
@jjhelmus, would you be able to take a look at this?

**Comment by jjhelmus** [comment]
Thanks for putting this together @mike-wendt.
I'm starting a build on our build worker now.  Will have a look at the package contents when they finish.

**Comment by jakirkham** [comment]
Any news on the build? How do the packages look?

**Comment by jjhelmus** [comment]
> Any news on the build? How do the packages look?

The linux-64 package built fines and looks good. I'm uploading it now and it should be available in `defaults` shortly.

The win-64 build failed, I need to log into a worker to get a better idea on the cause.

**Comment by mike-wendt** [comment]
> The win-64 build failed, I need to log into a worker to get a better idea on the cause.

Yeah @jjhelmus sorry I should have clarified I only built/tested linux.

**Comment by jjhelmus** [comment]
No problem.  I'm merge this and figure out the Windows build.

**Comment by jakirkham** [comment]
Thanks @jjhelmus! 😀

**Comment by jakirkham** [comment]
How would we go about updating `cudnn` as well?

**Comment by jakirkham** [comment]
> How would we go about updating `cudnn` as well?

FWIW we would be willing to help if you can guide us @jjhelmus 🙂

**Comment by jjhelmus** [comment]
Right now the `cudnn` recipes refer to some Anaconda, Inc internal information which needs to be protected.  I need to sanitize these before making the recipes publicly available.    

The major sticking point is that I have not found a reliable URL which allows the CuDNN installers to be downloaded without requiring authetication.  In the past I've needed to authenticate into the NVIDIA site, download the installer and then stage them to an internal server.  If there a method which can be used to avoid this?

**Comment by jjhelmus** [comment]
The cudnn recipe can now be found in the [cudnn-feedstock](https://github.com/AnacondaRecipes/cudnn-feedstock) repository.  I'm staging the installers to an internal server and will start builds once that finished.

**Comment by jakirkham** [comment]
Thanks Jonathan! That is greatly appreciated 😄

**Comment by jjhelmus** [comment]
cudnn 7.6.5 packages are now available for CUDA 9.0, 9.2, 10.0, 10.1 and 10.2.

**Pull request merged**
